name: "Receive Pull Request"

on:
  pull_request:
    types:
      [opened, synchronize, reopened]

jobs:
  test-pr:
    name: "Test if pull request is valid"
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check-pr.outputs.VALID }}
      MSG: ${{ steps.check-pr.outputs.MSG }}
    steps:
      - name: "Check PR"
        id: check-pr
        uses: carpentries/actions/check-valid-pr@add-invalid-hash
        with:
          pr: ${{ github.event.number }}
          invalid-hash: 54cff2e15d1ea86c005a5d6cc8cc041ee11ae7fc 

  build-md-source:
    name: "Build markdown source files"
    needs: test-pr
    runs-on: ubuntu-latest
    if: ${{ needs.test-pr.outputs.is_valid == 'true' }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv/
      CHIVE: ${{ github.workspace }}/site/chive
      PR: ${{ github.workspace }}/site/pr
      MD: ${{ github.workspace }}/site/built
    steps:
      - name: "Check Out Main Branch"
        uses: actions/checkout@v2

      - name: "Check Out Staging Branch"
        uses: actions/checkout@v2
        with:
          ref: md-outputs
          path: ${{ env.MD }}

      - name: "Set up R"
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: false

      - name: "Set up Pandoc"
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.11.4"

      - name: "Setup Lesson Engine"
        uses: carpentries/actions/setup-sandpaper@main
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}

      - name: "Setup Package Cache"
        uses: carpentries/actions/setup-lesson-deps@main
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}

      - name: "Validate and Build Markdown"
        id: build-site
        run: |
          sandpaper::package_cache_trigger(TRUE)
          sandpaper::validate_lesson(path = '${{ github.workspace }}')
          sandpaper:::build_markdown(path = '${{ github.workspace }}', quiet = FALSE)
        shell: Rscript {0}

      - name: "Generate Artifacts"
        id: generate-artifacts
        run: |
          sandpaper:::ci_bundle_pr_artifacts(
            repo         = '${{ github.repository }}',
            pr_number    = '${{ github.event.number }}',
            path_md      = '${{ env.MD }}',
            path_pr      = '${{ env.PR }}',
            path_archive = '${{ env.CHIVE }}',
            branch       = 'md-outputs'
          )
        shell: Rscript {0}

      - name: "Upload PR"
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ${{ env.PR }}

      - name: "Upload Diff"
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: ${{ env.CHIVE }}
          retention-days: 1
      
      - name: "Upload Build"
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: ${{ env.MD }}
          retention-days: 1

      - name: "Teardown"
        run: sandpaper::reset_site()
        shell: Rscript {0}

  comment-changed-workflow:
    name: "Comment if workflow files have changed"
    needs: test-pr
    runs-on: ubuntu-latest
    if: ${{ needs.test-pr.outputs.is_valid != 'true' }}
    steps:
      - name: "Record PR number"
        id: record
        run: |
          echo ${{ github.event.number }} > ${{ github.workspace }}/NR # 2022-03-02: artifact name fixed to be NR
      - name: "Upload PR number"
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ${{ github.workspace }}/NR
      - name: "Comment on PR"
        if: ${{ ! needs.test-pr.outputs.MSG }}
        id: comment-diff
        uses: carpentries/actions/comment-diff@main
        with:
          pr: ${{ github.event.number }}
          body: |
            This pull request contains modified workflows and no preview will be created.

            Unless these changes come from a trusted source, please inspect the changes for any malicious content.
      - name: "Comment on PR"
        if: ${{ needs.test-pr.outputs.MSG }}
        id: comment-diff-danger
        uses: carpentries/actions/comment-diff@main
        with:
          pr: ${{ github.event.number }}
          body: ${{ needs.test-pr.outputs.MSG }}
